### ISSUE TITLE
Contextual Alternates (calt) is being applied in reverse

### ISSUE THREAD

**Issue by arrowtype** [imohanvadivel/variable-font-playground#1]
This is a nice type tester! I did notice one issue, however: the feature `calt` (Contextual Alternates) is being applied in reverse.

I think it might be clearest to describe in a table...

What should happen by default | What currently happens by default | Good/Bad?
-- | -- | --
calt checkbox should be checked | calt checkbox is checked | ✅
In CSS, calt should be 1 | In CSS, calt is 0 | ❌
In font, calt should be active | In font, calt is deactivated | ❌

## Screenshots

This font should have no top serif on the `h` in the `Th` pair (it clashes, and this is kind of like a ligature, but better). This is done with the `calt` feature. However, this is only shown when the calt checkbox is unchecked.

![image](https://user-images.githubusercontent.com/45946693/123476365-9c75ad80-d5ca-11eb-8477-070a072e63f5.png)

![image](https://user-images.githubusercontent.com/45946693/123476401-a8616f80-d5ca-11eb-97d3-92cb93863f5c.png)

## Fixing it

Currently, the CSS `--calt:1;` is set when the calt checkbox is unchecked, overriding the app’s default of `--calt:0;`. That should be reversed.

**Comment by imohanvadivel** [comment]
Thanks for raising the issue,
I planned to enable calt by default, but forget to enable them in script.

Now it should work as intended :)
