### ISSUE TITLE
Live site is down

### ISSUE THREAD

**Issue by davelab6** [imohanvadivel/variable-font-playground#4]
https://mohanvadivel.com/projects/font-playground/ is down

**Comment by freder** [comment]
it's actually https://mohanvadivel.com/projects/variable-font-playground/ it seems

**Comment by imohanvadivel** [comment]
Recently I had updated some directories when switching over to 11ty.
I forgot to handle redirects, will update them shortly :)

You can access them here, https://mohanvadivel.com/projects/variable-font-playground/
