### ISSUE TITLE
Enable drop in for static fonts

### ISSUE THREAD

**Issue by weiweihuanghuang** [imohanvadivel/variable-font-playground#5]
I think this is such a nice font tester that it would be great to be able to drop in static fonts. I tried to make an edit but unfortunately couldn't understand where.

**Comment by imohanvadivel** [comment]
I can't get you, could you elaborate your issue.

BTW, It does support static font, you can drop in your static font and test its opentype features.
Which type of font extension, are you finding the issue with?
If possible could you share me the font, I'll look into it.

**Comment by weiweihuanghuang** [comment]
Sorry, basically I meant it would be good for it to support static fonts, but I didn't realise it was supported already. When I dragged the following OTF in, it merely changed the weight of the already set variable font. 


[WorkSans153-Regular.otf.zip](https://github.com/imohanvadivel/variable-font-playground/files/10752084/WorkSans153-Regular.otf.zip)

It seems to do with the font name having a number at the end, because when I remove the number it works.

**Comment by imohanvadivel** [comment]
Yes, It does seem to have the issue!
Thanks for reporting. I will look into this issue by this weekend.

Also, I'm planning to add more feature like
- Glyph Inspector
- Rich font metadata (listing language support and font metrics)
- Switching the font parsing library from JS to WASM (it will improve the performance by at least 3x)

If you have any other suggestion, kindly let me know :)

**Comment by imohanvadivel** [comment]
Hi @weiweihuanghuang, the issue should be fixed by now.
Please do a hard refresh on the page and try it out.

Let me know, if you still face the issue.

**Comment by weiweihuanghuang** [comment]
Amazing, it works! Thank you.
